services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: user
      POSTGRES_DB: todos
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
